# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import time
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
data = pd.read_csv('output_data/cities.csv')

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)
locations = data[['Lat','Lng']]
humidity = data['Humidity']

In [5]:
fig = gmaps.figure()

heatLayer = gmaps.heatmap_layer(locations, weights=humidity, max_intensity=max(humidity))

fig.add_layer(heatLayer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# max temperature between 60 and 85 degrees
# wind speed less than 10 mph
# cloudiness less than 5%

vacation_locations = data.loc[
    (data['Max Temp']>=60) & 
(data['Max Temp']<=85) &
(data['Wind Speed']<10) &
(data.Cloudiness<=5) &
(data.Humidity<85)].dropna()

# vacation_locations = vacation_locations.head
vacation_locations = vacation_locations.head(10)

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
vacation_locations['Hotel Name']=''
vacation_locations

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
55,55,Arlit,18.7369,7.3853,82.02,12,2,2.21,NE,1635117800,
72,72,Buraydah,26.3260,43.9750,72.05,29,0,6.17,SA,1635117825,
76,76,Santa Fe,-31.6333,-60.7000,72.99,39,0,1.99,AR,1635117678,
81,81,Cidreira,-30.1811,-50.2056,61.77,65,0,5.97,BR,1635117838,
89,89,Morondava,-20.2833,44.2833,72.36,61,0,4.79,MG,1635117853,
91,91,Abu Dhabi,24.4667,54.3667,78.82,83,0,3.44,AE,1635117854,
105,105,Hit,33.6416,42.8251,68.99,25,0,8.39,IQ,1635117880,
132,132,Keti Bandar,24.1447,67.4497,77.61,61,0,5.79,PK,1635117921,
166,166,Manawar,22.2333,75.0833,71.42,56,0,2.80,IN,1635117973,
179,179,Repatriacion,-25.5333,-55.9500,60.44,72,0,4.79,PY,1635117990,

In [8]:

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    'radius':5000,
    'type':'lodging',
    'keyword': 'hotel',
    'key':g_key}
    
for index, row in vacation_locations.iterrows():
    lat = row['Lat']
    lon = row['Lng']
    city = row['City']
    
    params['location']= f'{lat},{lon}'
                    
    response = requests.get(base_url, params=params).json()
    
    try:
        vacation_locations.loc[index,'Hotel Name'] = response['results'][0]['name']
        print(f'Searching for nearest hotel in {city}')
    except (KeyError, IndexError):
        print(f'Cannot find a hotel in {city}.')
    
    time.sleep(1)

#when using the 'in' iterates through columns tip:reset index, iterrows()

Searching for nearest hotel in Arlit
Searching for nearest hotel in Buraydah
Searching for nearest hotel in Santa Fe
Searching for nearest hotel in Cidreira
Searching for nearest hotel in Morondava
Searching for nearest hotel in Abu Dhabi
Searching for nearest hotel in Hit
Cannot find a hotel in Keti Bandar.
Searching for nearest hotel in Manawar
Cannot find a hotel in Repatriacion.

In [9]:
vacation_locations = vacation_locations.loc[:,{'City','Country','Lat','Lng','Hotel Name'}]
vacation_locations

,Country,City,Hotel Name,Lng,Lat
55,NE,Arlit,Hôtel Temet,7.3853,18.7369
72,SA,Buraydah,Best Western Plus Buraidah,43.9750,26.3260
76,AR,Santa Fe,Puerto Amarras Hotel & Suites,-60.7000,-31.6333
81,BR,Cidreira,Hotel Castelo,-50.2056,-30.1811
89,MG,Morondava,Palissandre Cote Ouest resort & SPA,44.2833,-20.2833
91,AE,Abu Dhabi,Emirates Palace,54.3667,24.4667
105,IQ,Hit,جواد كاظم,42.8251,33.6416
132,PK,Keti Bandar,,67.4497,24.1447
166,IN,Manawar,Hotel Keshar Residency,75.0833,22.2333
179,PY,Repatriacion,,-55.9500,-25.5333

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in vacation_locations.iterrows()]
locations = vacation_locations[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content= hotel_info)

fig.add_layer(markers)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))